<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 * Template Name: About Template
 */

//
get_header();
?>
<div class="subpage">
    <div class="sub_banner ">
        <div class="container">           
            <?php $lanCode = get_locale(); ?>
            <div class="row">
                <div class="col-md-9">
                    <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                    <?php if ($lanCode == 'en_US') { ?>
                        <p><a href="">Dr. Eri's Philosophy</a> / <span>First time's visit</span> /
                            <span> Cilnic news</span></p>
                    <?php } else { ?>
                        <p>&nbsp;</p>
                    <?php } ?>
                </div>
                <div class="col-md-3">
                    <form role="search" method="get" action="<?php echo esc_url( home_url( '/' ) ) ?>">
                        <input type="search" class="ip-search" placeholder="<?php echo esc_attr_x( 'Search &hellip;', 'placeholder' ) ?>" value="<?php echo get_search_query() ?>" name="s" title="<php echo esc_attr_x( 'Search for:', 'label' ) ?>" />
                        <input type="hidden" name="paged" value="1" />
                    </form>
                </div>
           </div>
        </div>
    </div>
    <div class="sub_content about">
        <div class="container">
            <div class="row">
            <?php
                do_action('genesis_before_content_sidebar_wrap');
                do_action('genesis_before_content');
                do_action('genesis_before_loop');
                do_action('genesis_loop');
                do_action('genesis_after_loop');
                do_action('genesis_after_content');
                do_action('genesis_after_content_sidebar_wrap');
            ?>
            <?php
            global $post, $more;
            $args = array();
            $defaults = apply_filters( 'woothemes_testimonials_default_args', array(
                'limit' 			=> 5,
                'per_row' 			=> null,
                'orderby' 			=> 'menu_order',
                'order' 			=> 'DESC',
                'id' 				=> 0,
                'display_author' 	=> true,
                'display_avatar' 	=> true,
                'display_url' 		=> true,
                'effect' 			=> 'fade', // Options: 'fade', 'none'
                'pagination' 		=> false,
                'echo' 				=> true,
                'size' 				=> 90,
                'title' 			=> '',
                'before_title' 		=> '<h2>',
                'after_title' 		=> '</h2>',
                'category' 			=> 0,
            ) );

            $args = wp_parse_args( $args, $defaults );

            // Allow child themes/plugins to filter here.
            $args = apply_filters( 'woothemes_testimonials_args', $args );
            $html = '';


            // The Query.
            $query = woothemes_get_testimonials( $args );

            $count = 0;
            $classFirst = true;
            $background = array(
                '0,0,0,.2',
                '77,5,51,.2',
                '145,169,216,.2'
            );
            ?>
            <div class="col-md-12">
                <div class="client-v">
                    <div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="3000">
                        <ol class="carousel-indicators">
                            <?php foreach ( $query as $index => $post ):?>
                                <li data-target="#fade-quote-carousel" data-slide-to="<?php echo $index;?>" class="<?php if($classFirst){echo "active"; $classFirst = false; }?>"></li>
                            <?php endforeach ?>
                        </ol>
                        <!-- Carousel items -->
                        <div class="carousel-inner">
                            <?php $classFirst = true;?>
                            <?php foreach ( $query as $index => $post ):?>
                                <?php setup_postdata( $post );?>
                                <div class="<?php if($classFirst){echo "active"; $classFirst = false; }?> item">
                                    <h2><?php echo get_the_title( $post );?></h2>
                                    <div class="profile-circle" style="background-color: rgba(<?php echo $background[$index%3];?>);">
                                        <?php echo $post->image;?>
                                    </div>
                                    <?php echo  apply_filters( 'woothemes_testimonials_content', apply_filters( 'the_content', get_the_content( __( 'Read full testimonial...', 'our-team-by-woothemes' ) ) ), $post );?>
                                </div>
                                <?php wp_reset_postdata();?>
                            <?php endforeach ?>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
    <?php if($lanCode == 'ja'){?>
    <div class="examination">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h3>クリニック初心者の方に、当院での診察の流れをご説明します。</h3>
                </div>
                <div class="col-md-4">
                    <a href="">はじめてのクリニック</a>
                </div>
            </div>
        </div>
    </div>
    <?php } ?>
</div>



<?php
    get_footer();
?>