<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Press Post Template
get_header();
?>

 <div class="subpage" id="menu">
    <div class="sub_banner body">
        <div class="container">                    
            <div class="row">
                  <div class="col-md-9">
                     <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                  </div>
                  <div class="col-md-3">
                     <input type="text" class="ip-search" placeholder="Search" style="font-family: ts-unused;">
                  </div>
               </div>
        </div>
    </div>
            
    <div class="sub_content" id="room_dr">
        <div class="container">
                 <div class="row">  
                  <div class="col-md-9">
                     <h4 class="title_h4">クリニック紹介</h4>                            
                     <!-- Start Items medi -->
                       <?php $my_query = new WP_Query('post_type=press'); 
                            while ($my_query->have_posts()) : $my_query->the_post();?>
                           <div class="item-media">
                              <div class="col-left-m">
                                 <a href="#"><?php echo the_post_thumbnail(array(345,210));  ?></a>                                   
                                      <?php $attachments = new Attachments( 'attachments' ); 
                                         if( $attachments->exist() ){ ?>
                                            <div class="download-info">
                                          <?php while( $attachments->get()){?>                                            
                                                  <a href="<?php echo $attachments->url(); ?>"><img src="<?php echo get_site_url(); ?>/wp-content/themes/genesis-eri/img/sub/media/pdf.png" alt="">詳細を見る<i class="fa fa-download"></i></a>
                                          <?php } ?>                                          
                                          </div>
                                  <?php } ?>                                   
                                </div>
                              <div class="col-right-m">
                                 <h5><a href="#"><?php the_title(); ?></a></h5>
                                 <p class="info-view">
                                    <i class="fa fa-calendar"></i> 
                                    <?php echo  the_date(); ?> /                                          
                                    <?php //the_category('/',the_ID()); ?> 
                                    <?php $category = get_the_category(); 
                                      foreach($category as $categorys) {?>
                                         <a href="<?php echo get_category_link( $categorys->term_id ); ?>"><span><?php echo $categorys->name; ?></span></a> /
                                     <?php  } ?>                                  
                                 <?php echo the_content();?>
                              </div>
                           </div>
                        <?php  endwhile;  wp_reset_query(); ?>
                    <!-- End items media-->                    
                 </div>

                  <div class="col-md-3  right-page">
                     <div class="nav-left">
                      <h3>categories</h3>
                        <?php
                          $cat_items = get_categories();
                          $parent = array();
                          $child = array();
                          while (count($cat_items) > 0) {
                              $curentItem = array_shift($cat_items);
                              if ($curentItem->parent == 0) {
                                  $parent[] = $curentItem;
                              } else {
                                  if (!isset($child[$curentItem->parent])) {
                                      $child[$curentItem->parent] = array();
                                  }
                                  $child[$curentItem->parent][] = $curentItem;
                              }
                          }
                          foreach($parent as $menuParrent) {
                              echo '<h5>'.$menuParrent->cat_name.'</h5>';                                                                            
                              if (isset($child[$menuParrent->term_id]) && count($child[$menuParrent->term_id]) > 0) {
                                      echo "<ul class=\"nav-ct-l\">";
                                        foreach($child[$menuParrent->term_id] as $catChild){
                                          $link = get_category_link($catChild->term_id); 
                                      echo '<li>';
                                      echo  "<a href=".$link."><i class=\"fa fa-caret-right\"></i>".$catChild->cat_name."</a>";                                                                      
                                      echo  '</li>';
                                  }                                
                              }
                              echo    "</ul>";                           
                            }
                          ?>
                    </div>
            </div>              
        </div>
    </div>    
</div>

<?php
    get_footer();
?>