<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Media Post Template
get_header();
?>

 <div class="subpage" id="menu">
    <div class="sub_banner body">
        <div class="container">                    
            <div class="row">
                  <div class="col-md-9">
                     <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                  </div>
                  <div class="col-md-3">
                     <input type="text" class="ip-search" placeholder="Search" style="font-family: ts-unused;">
                  </div>
               </div>
        </div>
    </div>
            
    <div class="sub_content" id="room_dr">
        <div class="container">
                 <div class="row">  
                  <div class="col-md-9">
                     <h4 class="title_h4"><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h4>                            
                     <!-- Start Items medi -->
                     <?php
                        $paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
                        add_image_size('featuredImageCropped', 345,210 , true);
                        $my_query = new WP_Query( array( 'post_type' => 'post', 'posts_per_page' => 5, 'paged' => $paged ) );
                        while ($my_query->have_posts()) : $my_query->the_post();
                        ?>
                           <div class="item-media">
                                <div class="col-left-m">
                                   <?php if(has_post_thumbnail()){ ?>
                                        <a href="<?php the_permalink() ?>"><?php echo the_post_thumbnail('featuredImageCropped');  ?></a>                                   
                                    <?php }else{ ?>
                                      <a href="#"><img src="<?php echo get_bloginfo( 'stylesheet_directory' ); ?>/img/no-images.png" /></a>                                                                              
                                     <?php } ?>                                         
                                        <?php $attachments = new Attachments( 'attachments' ); 
                                           if( $attachments->exist() ){ ?>
                                              <div class="download-info">
                                              <?php while( $attachments->get()){?>                                            
                                                      <a onClick="window.open('<?php echo $attachments->url(); ?>')"><img src="<?php echo get_site_url(); ?>/wp-content/themes/genesis-eri/img/sub/media/pdf.png" alt="">詳細を見る<i class="fa fa-download"></i></a>
                                              <?php } ?>                                          
                                            </div>
                                    <?php } ?>                                   
                                  </div>
                              <div class="col-right-m">
                                 <h5><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h5>
                                 <p class="info-view">
                                    <i class="fa fa-calendar"></i> 
                                    <?php echo  the_date(); ?> /                                          
                                    <?php $category = get_the_category(); 
                                      foreach($category as $categorys) {?>
                                         <a href="<?php echo get_category_link( $categorys->term_id ); ?>"><span><?php echo $categorys->name; ?></span></a> /
                                     <?php  } ?>                                  
                                     </p>
                                 <?php echo get_the_content(); ?>
                              </div>

                           </div>
                        <?php  endwhile;  wp_reset_query(); ?>
                    <!-- End items media-->                          
                        <?php  echo paging_nav(); ?>                          
                 </div>

                  <div class="col-md-3  right-page">
                     <div class="nav-left">
                      <h3>Categories</h3>
                        <?php
                          $cat_items = get_categories();
                          $parent = array();
                          $child = array();
                          while (count($cat_items) > 0) {
                              $curentItem = array_shift($cat_items);
                              if ($curentItem->parent == 0) {
                                  $parent[] = $curentItem;
                              } else {
                                  if (!isset($child[$curentItem->parent])) {
                                      $child[$curentItem->parent] = array();
                                  }
                                  $child[$curentItem->parent][] = $curentItem;
                              }
                          }
                          foreach($parent as $menuParrent) {
                              echo '<h5>'.$menuParrent->cat_name.'</h5>';                                                                            
                              if (isset($child[$menuParrent->term_id]) && count($child[$menuParrent->term_id]) > 0) {
                                      echo "<ul class=\"nav-ct-l\">";
                                        foreach($child[$menuParrent->term_id] as $catChild){
                                          $link = get_category_link($catChild->term_id); 
                                      echo '<li>';
                                      echo  "<a href=".$link."><i class=\"fa fa-caret-right\"></i>".$catChild->cat_name."</a>";                                                                      
                                      echo  '</li>';
                                  }                                
                              }
                              echo    "</ul>";                           
                            }
                          ?>
                    </div>
            </div>          
        </div>                        
    </div>    
</div>

<?php
function paging_nav() {
      $paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
      $GLOBALS['wp_query'] = $my_query = new WP_Query( array( 'post_type' => 'post', 'posts_per_page' => 5, 'paged' => $paged ) );

      if ( $GLOBALS['wp_query']->max_num_pages < 2 ) {
        return;
     }    
    $paged        = get_query_var( 'paged' ) ? intval( get_query_var( 'paged' ) ) : 1;
    $pagenum_link = html_entity_decode( get_pagenum_link() );
    $query_args   = array();
    $url_parts    = explode( '?', $pagenum_link );

    if ( isset( $url_parts[1] ) ) {
        wp_parse_str( $url_parts[1], $query_args );
    }
    $pagenum_link = remove_query_arg( array_keys( $query_args ), $pagenum_link );
    $pagenum_link = trailingslashit( $pagenum_link ) . '%_%';

    $format  = $GLOBALS['wp_rewrite']->using_index_permalinks() && ! strpos( $pagenum_link, 'index.php' ) ? 'index.php/' : '';
    $format .= $GLOBALS['wp_rewrite']->using_permalinks() ? user_trailingslashit( 'page/%#%', 'paged' ) : '?paged=%#%';
    // Set up paginated links.
    $links = paginate_links( array(
        'base'     => $pagenum_link,        
        'total'    => $GLOBALS['wp_query']->max_num_pages,        
        'prev_text' => __( 'Pre', 'genesis-eri' ),
        'next_text' => __( 'Next', 'genesis-eri' ),
        'type'      => 'list',
    ) );
    if ( $links ) :
    ?>
   <div class="paging">
            <div class="pull-left">Showing: <?php echo $paged; ?> of <?php echo $GLOBALS['wp_query']->max_num_pages; ?> press</div>
            <div class="pull-right">     
                <?php echo $links; ?>                
            </div>
         </div>    
    <?php
    endif;  
    }
?>


<?php
    get_footer();
?>






