<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Price Template
get_header();
?>

<div class="subpage" id="menu">
  <div class="sub_banner body">
    <div class="container">                    
      <div class="row">
        <div class="col-md-9">
            <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
            <p>&nbsp;</p>
        </div>
        <div class="col-md-3">
          <input type="text" placeholder="Search" class="ip-search">
        </div>
      </div>
    </div>
  </div>

<div class="sub_content" id="men_dr">
  <div class="container">
    <div class="row"> 
      <div class="col-md-9">
        <?php echo do_shortcode("[huge_it_slider id ='29']"); ?>
        <div class="group-item-men">                                                  
           <?php
                do_action('genesis_before_content_sidebar_wrap');
                do_action('genesis_before_content');
                do_action('genesis_before_loop');
                do_action('genesis_loop');
                do_action('genesis_after_loop');
                do_action('genesis_after_content');
                do_action('genesis_after_content_sidebar_wrap');
           ?>      
        </div>            
      </div>   

      <div class="col-md-3  right-page">
            <div class="nav-left">
              <h3>MENU for MEN</h3>
              <ul class="nav-ct-l men">
                <li><a href="<?php get_site_url(); ?>/men/"><span><i class="fa fa-angle-right"></i>HOME</span></a></li>
                <?php query_posts( array( 'post_type' => 'men', 'showposts' => 100 ) );
if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
  <li><a href="<?php echo get_permalink() ?>"><i class="fa fa-angle-right"></i><?php the_title(); ?><?php get_the_ID(); ?></a></li>
<?php endwhile; endif; wp_reset_query(); ?>
  
  <li><a href="<?php get_site_url(); ?>/price"><i class="fa fa-angle-right"></i>料金表</a></li>

            </ul>
          </div>
        </div>
      </div>
    </div>  
  </div>
  </div>         
</div>         
<?php get_footer(); ?>