<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 * Template Name: Menu Template
 */


get_header();
?>
    <div class="subpage" id="menu">
        <div class="sub_banner ">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                        <p>&nbsp;</p>
                    </div>
                    <div class="col-md-3">
                        <form role="search" method="get" action="<?php echo esc_url(home_url('/')) ?>">
                            <input type="search" class="ip-search"
                                   placeholder="<?php echo esc_attr_x('Search &hellip;', 'placeholder') ?>"
                                   value="<?php echo get_search_query() ?>" name="s"
                                   title="<php echo esc_attr_x( 'Search for:', 'label' ) ?>"/>
                            <input type="hidden" name="paged" value="1"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="sub_content" id="menu_dr">
            <div class="container">            	
            	
                <?php
                do_action('genesis_before_content_sidebar_wrap');
                do_action('genesis_before_content');
                do_action('genesis_before_loop');
                do_action('genesis_loop');
                do_action('genesis_after_loop');
                do_action('genesis_after_content');
                do_action('genesis_after_content_sidebar_wrap');
                $value = get_post_meta(get_the_ID(), '_category_for_pages_meta_value_key', true);
                $args = array(
                    'type' => 'post',
                    'child_of' => $value,
                    'parent' => "",
                    'orderby' => 'id',
                    'order' => 'ASC',
                    'hide_empty' => 0,
                    'hierarchical' => 1,
                    'exclude' => '',
                    'include' => '',
                    'number' => '',
                    'taxonomy' => 'category',
                    'pad_counts' => false
					
                );

                $categories = get_categories($args);
                $locale = get_locale();
                if ("en_US" == $locale) {
                    $locale = "en";
                }
                ?>               

                    <div class="content-menu">
                        <?php foreach (array_chunk($categories,3) as $row):?>
                        	<div class="row">
								<?php foreach ($row as $index => $category): ?>
                                <?php
                                $args = array(
                                    'posts_per_page' => 20,
                                    'offset' => 0,
                                    'category' => $category->cat_ID,
                                    'category_name' => '',
                                    'orderby' => 'post_date',
                                    'order' => 'DESC',
                                    'include' => '',
                                    'exclude' => '',
                                    'meta_key' => '',
                                    'meta_value' => '',
                                    'post_type' => 'service',
                                    'post_mime_type' => '',
                                    'post_parent' => '',
                                    'post_status' => 'publish',
                                    'suppress_filters' => true
                                );
                                $posts_array = get_posts($args);
                                ?>
                                <div class="col-md-4">                                	
                                    <div class="menu-ct fix-heigt<?php echo $index + 1; ?>">
                                        <div class="col-header col<?php echo $index + 1; ?>">
                                            <h5><img src="http://eri-clinic.vn/wp-content/uploads/service-icon_01.png" class="pull-left"/>&nbsp;&nbsp;<?php echo $category->cat_name; ?></h5>
                                            <p><span class="count-nb"><?php echo count($posts_array); ?></span></p>
                                        </div>
                                        <div class="col-mn-content">
                                            <div class="scroll-pane">
                                                <ul>
                                                    <?php foreach ($posts_array as $post): ?>
                                                        <?php //setup_postdata( $post );?>
                                                        <li>
                                                            <a href="<?php echo get_permalink($post->ID); ?>" title="<?php echo get_the_title($post); ?>">
                                                                <i class="fa fa-map-marker"></i>
                                                                <?php echo get_the_title($post); ?>
                                                            </a>
                                                        </li>                                                        
                                                        <?php //wp_reset_postdata();?>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    
            	</div>
            </div>
        </div>
    </div>
<?php
get_footer();
?>