<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Men Template
get_header();
?>

<div class="subpage" id="menu">
    <div class="sub_banner body">
        <div class="container">                    
            <div class="row">
                  <div class="col-md-9">
                     <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                  </div>
                  <div class="col-md-3">
                     <input type="text" class="ip-search" placeholder="Search" style="font-family: ts-unused;">
                  </div>
               </div>
        </div>
    </div>
    <?php function getMenuForMenpage($menu_id){
           $menu_items =  wp_get_nav_menu_items($menu_id);
                  if($menu_items){
                        while (count($menu_items) > 0) {
                              $curentItem = array_shift($menu_items);
                              if ($curentItem->menu_item_parent == 0) {
                                  $parent[] = $curentItem;
                              } else {
                                  if (!isset($child[$curentItem->menu_item_parent])) {
                                      $child[$curentItem->menu_item_parent] = array();
                                  }
                                  $child[$curentItem->menu_item_parent][] = $curentItem;
                              }
                          }                         
                          foreach($parent as $menuParrent) { ?>
                              <h3><?php echo $menuParrent->post_title; ?></h3>
                                <ul class="nav-ct-l men">
                                    <?php foreach($child[$menuParrent->ID] as $menuChild){                                                                                                                                                     
                                            if($menuChild->attr_title == 'disable'){                                                                       
                                              echo '<li><a href=""><span><i class="fa fa-angle-right"></i>'.$menuChild->post_title.'</span></a></li>';                         
                                            }else{
                                              echo '<li><a href=""><i class="fa fa-angle-right"></i>'.$menuChild->post_title.'</a></li>';    
                                            } 
                                          }
                                        } 
                                   ?>
                            </ul>
              <?php } } ?> 
      
     <div class="sub_content" id="men_dr">
        <div class="container">
                 <div class="row">
                       <?php
                          do_action('genesis_before_content_sidebar_wrap');
                          do_action('genesis_before_content');
                          do_action('genesis_before_loop');
                          do_action('genesis_loop');
                          do_action('genesis_after_loop');
                          do_action('genesis_after_content');
                          do_action('genesis_after_content_sidebar_wrap');
                        ?>
                    <div class="col-md-3  right-page">
                       <div class="nav-left">
                            <?php echo getMenuForMenpage('sub_page_men_ja');?>
                       </div>
                   </div>
              </div>              
        </div>
    </div>    
</div>



<?php
    get_footer();
?>