<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Beginer Template
get_header();
?>
<div class="subpage">
    <div class="sub_banner ">
        <div class="container">           
            <?php $lanCode = get_locale();             
            ?>
            <div class="row">
              <div class="col-md-9">
                 <h3>About Dr. Eri</h3>                               
                 <p><span>Dr. Eri's Philosophy</span> / <span>First time's visit</span> / <span>Cilnic news</span></p>
               
                         
              </div>            
                  <div class="col-md-3">
                     <input type="text" class="ip-search" placeholder="Search">
                  </div>              
           </div>
        </div>
    </div>
  <div class="sub_content" id="about_dr">
            <div class="container">
               <div class="row">
            <?php
                do_action('genesis_before_content_sidebar_wrap');
                do_action('genesis_before_content');
                do_action('genesis_before_loop');
                do_action('genesis_loop');
                do_action('genesis_after_loop');
                do_action('genesis_after_content');
                do_action('genesis_after_content_sidebar_wrap');
            ?>
          </div>
        </div>
    </div>   
</div>



<?php
    get_footer();
?>