<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Body Template
get_header();
?>
<div class="subpage">
    <div class="sub_banner body">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                </div>
                <div class="col-md-3">
                    <ul>
                        <li><a href=""><i class="fa fa-circle"></i>肌のお悩み</a></li>
                        <li><a href=""><i class="fa fa-circle"></i>顔のお悩み</a></li>
                        <li><a href=""><i class="fa fa-circle"></i>顔のお悩み</a></li>
                        <li><a href=""><i class="fa fa-circle"></i>内科的なお悩</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="sub_content body">
        <div class="container">
            <?php
                do_action('genesis_before_content_sidebar_wrap');
                do_action('genesis_before_content');
                do_action('genesis_before_loop');
                do_action('genesis_loop');
                do_action('genesis_after_loop');
                do_action('genesis_after_content');
                do_action('genesis_after_content_sidebar_wrap');
            ?>
        </div>
    </div>
</div>
<?php
get_footer();
?>
<script type="text/javascript" id="sourcecode">
    $(function () {
        var $content = $(".probtable").hide();
        $(".tglbtn").on("click", function (e) {
            var SH = this.SH ^= 1; // "Simple toggler"
            $(this).text(SH ? '▲適応メニューを閉じる' : '▼適応メニューを開く')
            $(this).toggleClass("expanded");
            $(this).next($content).slideToggle();
        });

    });
</script>