<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Service Template
get_header();
?>
<div class="subpage">    
    <div class="sub_banner body">
        <div class="container">                    
            <div class="row">
                  <div class="col-md-9">
                     <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>                     
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                  </div>
                  <div class="col-md-3">
                     <input type="text" style="font-family: ts-unused;" placeholder="Search" class="ip-search">
                  </div>
               
            </div>    
        </div>
    </div>
</div>

<div id="service-detail" class="sub_content service-detail-1">
    <div class="container">
                  <?php
                    do_action('genesis_before_content_sidebar_wrap');
                    do_action('genesis_before_content');
                    do_action('genesis_before_loop');
                    do_action('genesis_loop');
                    do_action('genesis_after_loop');
                    do_action('genesis_after_content');
                    do_action('genesis_after_content_sidebar_wrap');
                ?>      
        </div>
    </div>
                      
                
        <div class="examination">
            <div class="container">
               <div class="row">
                  <div class="col-md-8">
                     <h3>クリニック初心者の方に、当院での診察の流れをご説明します。</h3>
                  </div>
                  <div class="col-md-4">
                     <a href="">はじめてのクリニック</a>
                  </div>
               </div>
            </div>
         </div>

<?php
    get_footer();

?>
 <script type="text/javascript" id="sourcecode">
         $(function()
         {
            $('nav .navbar li').hover(function() {
                  $(this).find('.dropdown-menu').first().stop(true, true).slideDown(150);
                  $(this).addClass('open');
                }, function() {
                  $(this).find('.dropdown-menu').first().stop(true, true).slideUp(105);
                  $(this).removeClass('open');
                });
            $('.scroll-pane').jScrollPane();
         });
      </script>
      <script type="text/javascript">
            $(document).ready(function ($) {
                // delegate calls to data-toggle="lightbox"
                $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
                    event.preventDefault();
                    return $(this).ekkoLightbox({
                        onShown: function() {
                            if (window.console) {
                                return console.log('Checking our the events huh?');
                            }
                        },
                  onNavigate: function(direction, itemIndex) {
                            if (window.console) {
                                return console.log('Navigating '+direction+'. Current item: '+itemIndex);
                            }
                  }
                    });
                });
            });
        </script>
<script type="text/javascript" src="//typesquare.com/accessor/script/typesquare.js?CiYo65fd~Tg%3D" charset="utf-8"></script>        