
<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Home Template
get_header(); ?>
<div class="contaner_content container">
<?php 
	do_action( 'genesis_before_content_sidebar_wrap' );
	do_action( 'genesis_before_content' );
	do_action( 'genesis_before_loop' );
	do_action( 'genesis_loop' );
	do_action( 'genesis_after_loop' );
	do_action( 'genesis_after_content' );
	do_action( 'genesis_after_content_sidebar_wrap' );
?>
</div>
<?php  get_footer(); ?>

