<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

get_header();
?>
<div class="subpage">    
    <div class="sub_banner body">
        <div class="container">                    
            <div class="row">
                  <div class="col-md-9">
                     <h3><?php echo apply_filters('genesis_post_title_text', get_the_title()); ?></h3>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                  </div>
                  <div class="col-md-3">
                     <input type="text" style="font-family: ts-unused;" placeholder="Search" class="ip-search">
                  </div>               
            </div>    
        </div>
    </div>


<div class="sub_content" id="product_detail_dr">
            <div class="container">               
                <?php
                    do_action('genesis_before_content_sidebar_wrap');
                    do_action('genesis_before_content');
                    do_action('genesis_before_loop');
                    do_action('genesis_loop');
                    do_action('genesis_after_loop');
                    do_action('genesis_after_content');
                    do_action('genesis_after_content_sidebar_wrap');
                ?>              
        </div>
</div>
</div>
<style type="text/css">
.entry-header, .entry-meta{
  display: none;
}
</style>  
 <script type="text/javascript" id="sourcecode">
         $(function()
         {
            $('nav .navbar li').hover(function() {
                 $(this).find('.dropdown-menu').first().stop(true, true).slideDown(150);
                 $(this).addClass('open');
               }, function() {
                 $(this).find('.dropdown-menu').first().stop(true, true).slideUp(105);
                 $(this).removeClass('open');
               });
            $('.scroll-pane').jScrollPane();
         });
         $(function()
         {
           $('.view_history[data-type="multi"] .item').each(function(){
            var next1 = $(this).next();
            if (!next1.length) {
              next1 = $(this).siblings(':first');
            }
            next1.children(':first-child').clone().appendTo($(this));
            for (var i=0;i<3;i++) {
              next1=next1.next();
              if (!next1.length) {
                next1 = $(this).siblings(':first');
              }
              next1.children(':first-child').clone().appendTo($(this));
            }
          });
         });
      </script>
<?php
    get_footer();

?>
 